export default {
	PRIMARY_COLOR: '#0C8711',
	PRIMARY_DARK: '#0A6B0E',
	PRIMARY_LIGHT: '#4CAF50',
	SECONDARY_COLOR: '#C9E0AD',
	SECONDARY_LIGHT: '#E8F5E9',
	FONT_SIZE_SMALL: 12,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 24,
	FONT_SIZE_TITLE: 26,
	FONT_WEIGHT_LIGHT: '300',
	FONT_WEIGHT_MEDIUM: '500',
	FONT_WEIGHT_BOLD: '700',
	BACKGROUND_COLOR_LIGHT: '#f8fbf8',
	BACKGROUND_COLOR_WHITE: '#ffffff',
	LIGHT_GRAY_COLOR: '#f5f5f5',
	DARK_GRAY_COLOR: '#333333',
	CONTAINER_PADDING: 20
};